### ISSUE TITLE
Dark mode doesn't allow user to edit or close add config window

### ISSUE THREAD

**Issue by ninaforsyth** [nginx/docker-extension#3]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/11824801/226446883-70d961c7-0f74-4d1d-a619-13ed69771813.png">

When using dark mode, you can't select a new configuration, you can't edit the configuration, and you can't exit this window.

**Comment by tippexs** [comment]
Hi @ninaforsyth - thanks for the report. This looks like a bug with the dark mode settings. We will have a look on patch asap.

**Comment by tippexs** [comment]
Was fixed in version 0.0.2
